if (!require(shinyWidgets)) {install.packages("shinyWidgets")};  library(shinyWidgets)
if (!require(stringr)) {install.packages("stringr")};  library(stringr)
if (!require(dplyr)){install.packages("dplyr")}; library(dplyr)
if (!require(tidytext)){install.packages('tidytext')}; library(tidytext)
if (!require(shiny)){install.packages('shiny')}; library(shiny)
if (!require(magrittr)){install.packages('magrittr')}; library(magrittr)
if (!require(stringi)){install.packages('stringi')}; library(stringi)
if (!require(visNetwork)){install.packages('visNetwork')}; library(visNetwork)
if (!require(slam)){install.packages('slam')}; library(slam)
if (!require(wordcloud)){install.packages('wordcloud')}; library(wordcloud)
if (!require(tokenizers)){install.packages('tokenizers')}; library(tokenizers)
if (!require(tm)){install.packages('tm')}; library(tm)
if (!require(text2vec)){install.packages('text2vec')}; library(text2vec)
if (!require(DT)){install.packages('DT')}; library('DT')
if (!require(tidyr)){install.packages('tidyr')}; library(tidyr)
if (!require(igraph)){install.packages('igraph')}; library(igraph)
