try(require("shiny")||install.packages("shiny"))
try(require("devtools")||install.packages("devtools"))
library('devtools')
try(require("tm")||install_version("tm", version = "0.6-2", repos = "http://cran.us.r-project.org"))
try(require("wordcloud")||install.packages("wordcloud"))
# try(require("qdap")||install.packages("qdap"))
try(require("RWeka")||install.packages("RWeka"))
try(require("igraph")||install.packages("igraph"))

library("shiny")
library("tm")
library("wordcloud")
# library("qdap")
library("RWeka")
library("igraph")
